kotlin.code.style=official
version=0.0.2
org.gradle.daemon=false
org.gradle.test.parallel=true
org.gradle.jvmargs=-Xmx8g -Xms512m
# Kotlin
kotlinVersion=2.0.21
coroutinesVersion=1.7.3
# Linting
detektVersion=1.23.4
spotlessVersion=6.22.0
# Spring
springBootVersion=3.4.1
springDependencyManagementVersion=1.1.7
# Other
springdocVersion=1.6.12
sentryLogbackVersion=6.5.0
logstashLogbackEncoderVersion=7.2
springfox=2.10.5
slf4jVersion=2.0.5
opentelemetryExtensionKotlin=1.42.1